apiVersion: v1
data:
  fixownership.sh: Y2hvd24gcm9vdDoxMDAwNjgwMDAwIC9ob21lL3NmdHB1c2VyL2ZpbGVzCmNob3duIHJvb3Q6MTAwMDY4MDAwMCAvaG9tZS9zZnRwdXNlci9hcmNoaXZlcwpjaG1vZCA3NzAgL2hvbWUvc2Z0cHVzZXIvZmlsZXMKY2htb2QgNzcwIC9ob21lL3NmdHB1c2VyL2FyY2hpdmVzCnNlZCAtaSAnMXMvXi9QYXNzd29yZEF1dGhlbnRpY2F0aW9uIG5vXG5DaGFsbGVuZ2VSZXNwb25zZUF1dGhlbnRpY2F0aW9uIG5vXG4vJyAvZXRjL3NzaC9zc2hkX2NvbmZpZwo=
kind: Secret
metadata:
  creationTimestamp: "2021-04-09T12:51:44Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:type: {}
    manager: oc
    operation: Update
    time: "2021-04-09T12:51:44Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:fixownership.sh: {}
    manager: Mozilla
    operation: Update
    time: "2021-06-21T14:46:02Z"
  name: changeowner
  namespace: jsoningestion
  resourceVersion: "79344105"
  selfLink: /api/v1/namespaces/jsoningestion/secrets/changeowner
  uid: 224b48d5-8d47-42cf-9c3b-781d5c003cda
type: Opaque
