apiVersion: v1
kind: Service
metadata:
  labels:
    app: jsoningestion
  name: jsoningestion-service
  namespace: jsoningestion 
spec:
  ports:
    - name: jiports
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jsoningestion 
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
