apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsonarchive-pvc
  namespace: jsoningestion 
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-file-gold 
