apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoicmdhaG9ja2V5MyIsInBhc3N3b3JkIjoiVHVlc2RhMHk/IiwiYXV0aCI6ImNtZGhhRzlqYTJWNU16cFVkV1Z6WkdFd2VUOD0iLCJlbWFpbCI6IiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2021-06-08T15:39:42Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: Mozilla
    operation: Update
    time: "2021-06-08T15:42:30Z"
  name: jsoningestionsecret
  namespace: jsoningestion
  resourceVersion: "5236671"
  selfLink: /api/v1/namespaces/jsoningestion/secrets/jsoningestionsecret
  uid: 80a97a39-a61f-4580-9139-ebd8cc54e336
type: kubernetes.io/dockerconfigjson
