apiVersion: v1
data:
  outputpathkey: L2ZpbGVz
kind: Secret
metadata:
  creationTimestamp: "2021-06-10T18:05:01Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:outputpathkey: {}
      f:type: {}
    manager: Mozilla
    operation: Update
    time: "2021-06-15T18:14:15Z"
  name: outputpath
  namespace: jsoningestion
  resourceVersion: "8629213"
  selfLink: /api/v1/namespaces/jsoningestion/secrets/outputpath
  uid: be238751-760f-4e9b-bfd3-0dfcb94b0c2f
type: Opaque
