apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsoningest-pvc
  namespace: jsoningestion 
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: portworx-shared-gp3 
