apiVersion: v1
data:
  systemurlkey: Y3A0ZC1jcGQtY3A0ZC5zdGF0ZWZhcm0tY2ExMTFiYTM1YmEyZWFkMmMyOWU2ZGEyZTQ1ZTNjODYtMDAwMC51cy1zb3V0aC5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZA==
kind: Secret
metadata:
  creationTimestamp: "2021-06-10T17:57:07Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:systemurlkey: {}
      f:type: {}
    manager: Mozilla
    operation: Update
    time: "2021-06-10T17:57:07Z"
  name: systemurl
  namespace: jsoningestion
  resourceVersion: "6227896"
  selfLink: /api/v1/namespaces/jsoningestion/secrets/systemurl
  uid: fdc98e7f-ab5b-420c-9f85-391fca4f590b
type: Opaque
